/**
 * \file
 *
 * \brief Driver initialization.
 *
 (c) 2020 Microchip Technology Inc. and its subsidiaries.

    Subject to your compliance with these terms,you may use this software and
    any derivatives exclusively with Microchip products.It is your responsibility
    to comply with third party license terms applicable to your use of third party
    software (including open source software) that may accompany Microchip software.

    THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
    EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
    WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
    PARTICULAR PURPOSE.

    IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
    WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
    BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
    FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
    ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
    THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 */

/*
 * Code generated by START.
 *
 * This file will be overwritten when reconfiguring your START project.
 * Please copy examples or other code you want to keep to a separate file
 * to avoid losing it when reconfiguring.
 */

#include "driver_init.h"
#include <system.h>

/* Configure pins and initialize registers */
void OPERATIONAL_AMPLIFIER_0_initialization(void)
{

	// Disable digital input buffer
	PD3_set_isc(PORT_ISC_INPUT_DISABLE_gc);
	// Disable pull-up resistor
	PD3_set_pull_mode(PORT_PULL_OFF);
// Disable digital input buffer
PORTD_pin_set_isc(1,PORT_ISC_INPUT_DISABLE_gc);
// Disable pull-up resistor
PORTD_set_pin_pull_mode(1,PORT_PULL_OFF);
	// Disable digital input buffer
	PD2_set_isc(PORT_ISC_INPUT_DISABLE_gc);
	// Disable pull-up resistor
	PD2_set_pull_mode(PORT_PULL_OFF);

	// Disable digital input buffer
	PD7_set_isc(PORT_ISC_INPUT_DISABLE_gc);
	// Disable pull-up resistor
	PD7_set_pull_mode(PORT_PULL_OFF);

	// Disable digital input buffer
	PD5_set_isc(PORT_ISC_INPUT_DISABLE_gc);
	// Disable pull-up resistor
	PD5_set_pull_mode(PORT_PULL_OFF);

	// Disable digital input buffer
	PE3_set_isc(PORT_ISC_INPUT_DISABLE_gc);
	// Disable pull-up resistor
	PE3_set_pull_mode(PORT_PULL_OFF);
// Disable digital input buffer
PORTE_pin_set_isc(1,PORT_ISC_INPUT_DISABLE_gc);
// Disable pull-up resistor
PORTE_set_pin_pull_mode(1,PORT_PULL_OFF);
	// Disable digital input buffer
	PE2_set_isc(PORT_ISC_INPUT_DISABLE_gc);
	// Disable pull-up resistor
	PE2_set_pull_mode(PORT_PULL_OFF);

	OPERATIONAL_AMPLIFIER_0_init();
}

void EVENT_SYSTEM_0_initialization(void)
{

	EVENT_SYSTEM_0_init();
}

/* configure pins and initialize registers */
void DAC_0_initialization(void)
{

	// Disable digital input buffer
	DACOUT_set_isc(PORT_ISC_INPUT_DISABLE_gc);
	// Disable pull-up resistor
	DACOUT_set_pull_mode(PORT_PULL_OFF);

	DAC_0_init();
}

/* Configure pins and initialize registers */
void ADC_0_initialization(void)
{

	ADC_0_init();
}

void TIMER_0_initialization(void)
{

	// Set pin direction to output

	PE0_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	PE0_set_dir(PORT_DIR_OUT);

	/* set the alternate pin mux */

	PORTMUX.TCAROUTEA |= PORTMUX_TCA02_bm;

	TIMER_0_init();
}

void TIMER_1_initialization(void)
{

	TIMER_1_init();
}

/**
 * \brief System initialization
 */
void system_init()
{
	mcu_init();

	/* PORT setting on PE1 */

	// Set pin direction to output

	PORTF_set_pin_level(5, false);


		PORTF_set_pin_dir(5, PORT_DIR_OUT);

	OPERATIONAL_AMPLIFIER_0_initialization();

	CLKCTRL_init();

	EVENT_SYSTEM_0_initialization();

	SLPCTRL_init();

	CPUINT_init();

	DAC_0_initialization();

	ADC_0_initialization();

	TIMER_0_initialization();

	TIMER_1_initialization();

	BOD_init();
}
